### ISSUE TITLE
Reduction Operator Discarded When PrintAST Called

### ISSUE THREAD

**Issue by JCampbellBradley** [CSU-CS-Melange/AlphaZ#26]
When PrintAST is called on a system that has a reduction, the operator used in that reduction does not appear in the output of PrintAST. Two systems that are identical except for the operator used in their respective reductions will produce identical ASTs, when one would expect the outputs to differ with respect to the operator.

**Comment by lnarmour** [comment]
This is fixed. You should see `|+— ADD`,  `|+— MUL`, etc. in the outputs now.
