### ISSUE TITLE
Runtime Exception Thrown when Normalizing Already Normalized Reduction

### ISSUE THREAD

**Issue by JCampbellBradley** [CSU-CS-Melange/AlphaZ#27]
When calling NormalizeReduction on a reduction that is already in normal form, a RuntimeError is thrown with the message "This reduction is already normalized.", when we should expect the reduction to be left in its current form.

**Comment by lnarmour** [comment]
I agree, NormalizedReduction should just do nothing and exit cleanly without throwing any exceptions if the reduction is “already normalized". 

This is fixed.
